/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  static const String back = "assets/svg/icons/back.svg";
  static const String bell = "assets/svg/icons/bell.svg";
  static const String broadcast = "assets/svg/icons/broadcast.svg";
  static const String compass_off = "assets/svg/icons/compass_off.svg";
  static const String compass_on = "assets/svg/icons/compass_on.svg";
  static const String dislike = "assets/svg/icons/dislike.svg";
  static const String home_off = "assets/svg/icons/home_off.svg";
  static const String home_on = "assets/svg/icons/home_on.svg";
  static const String library_off = "assets/svg/icons/library_off.svg";
  static const String library_on = "assets/svg/icons/library_on.svg";
  static const String like = "assets/svg/icons/like.svg";
  static const String logo = "assets/images/logo.png";
  static const String plus = "assets/svg/icons/plus.svg";
  static const String save = "assets/svg/icons/save.svg";
  static const String search = "assets/svg/icons/search.svg";
  static const String share = "assets/svg/icons/share.svg";
  static const String subs_off = "assets/svg/icons/subs_off.svg";
  static const String subs_on = "assets/svg/icons/subs_on.svg";
  static const String upload = "assets/svg/icons/upload.svg";
  static const String wall_clock = "assets/svg/icons/wall-clock.svg";
}
